#!/bin/bash

echo "🚀 RuneSpoke Landing - Push to Vercel"
echo "====================================="
echo ""
echo "You have 5 commits ready to deploy:"
echo ""
git log --oneline -5
echo ""
echo "====================================="
echo ""
echo "Choose your push method:"
echo ""
echo "1. GitHub Desktop (Easiest)"
echo "   - Open GitHub Desktop"
echo "   - Select 'runespoke-landing' repository"
echo "   - Click 'Push origin' (5 commits)"
echo ""
echo "2. Personal Access Token"
echo "   - Create token at: https://github.com/settings/tokens"
echo "   - Select 'repo' scope"
echo "   - Run: git push https://RuneSpokeAdmin:YOUR_TOKEN@github.com/RuneSpokeAdmin/runespoke-landing.git main"
echo ""
echo "3. Use existing credentials"
echo "   - Try: git push origin main"
echo ""
echo "====================================="
echo ""
echo "After pushing, Vercel will automatically:"
echo "✅ Detect the changes"
echo "✅ Build the new version"
echo "✅ Deploy to https://runespoke-landing.vercel.app"
echo ""
echo "The deployment usually takes 1-2 minutes."
echo ""